### PR TITLE
Add Handler For SIGINT and SIGHUP

### PR DESCRIPTION
**Pull request by Love-Pengy**
Not quite done with this yet, but wanted to get your input as I've changed a good amount to get this working as intended and I also need to finish testing. The main goal of this was to add handling for both SIGINT (CTRL+C) and SIGHUP (closing the terminal). To do this though I moved the functions into a class, added a wrapper function and pulled the affirmations list into the global scope. Lmk if there's anything I can change to follow what you were already doing with the project I tried to follow the python way as you already were but I'm sure I missed some lol

### CODE REVIEW

**Comment by kiyubits** [comment]
honestly it looks really good, i kinda just speedran it when i made it but u def polished it up!!! 

i tried it myself and ye it seems to be working for ctrl + c and quitting, although the json file looked a little weird, like it duplicated the day number (90, 90) for two entries when i was testing it, which is weird cuz it should just look at the length of the json file.

but u may be still working on it so i'll let u cook, and i can test it more later on (i just briefly did it and it looked weird), might just be a me issue

one thing i kinda wanted to do was also to add terminal colours, like with the cat just to make it look nicer, tho if u wanna just improve the functionality then all g, i'll get to it eventually LOL

**Comment by Love-Pengy** [comment]
Weird, I tested it a bit last night and didn't have that issue but it could have also been I was a bit sleep deprived and missed it LMAO Was the weird output on CTRL+C, on terminal close, or both? Also absolutely! I was already planning on looking into making an animation for the lil cat but that might be a bit too much as I suck at art. I was going to section different changes into different issues tho so that it's not a bunch of changes in one so if you want to you could throw up some issues and I'll take a look at them~

**Comment by Love-Pengy** [comment]
Just tested it on my system everything seems to be working as intended! One note tho, when continuing a session it is currently intended to only be used when you accidentally close terminal or ctrl+c and will go immediately back to the session. Because of this if you come back at a later time it will add all the time from the old start time to the new end time. I'll probably spin up a new issue for adding breaks and what not to handle this case

**Comment by kiyubits** [comment]
sounds dope :D

**Pull request merged**
